script = $0
puts $0

puts "\n"
puts "These are my Makers Academy February Cohort fellow:\n\n"
puts "\tMario Gintili"
puts "\tMikhail Dubov"
puts "\tKarolis Noreika"
puts "\tMichael Sidon"
puts "\tCharles De Barros"
puts "\tRuslan Vikhor"
puts "\tToby Retallick"
puts "\tMark Mekhaiel"
puts "\tSarah Young"
puts "\tHannah Wight"
puts "\tKhushkaran Singh"
puts "\tRick Brunstedt"
puts "\tManjit Singh"
puts "\tAlex Gaudiosi"
puts "\tRoss Hepburn"
puts "\tNatascia Marchese"
puts "\tTiffanie Chia"
puts "\tMatthew Thomas"
puts "\tFreddy McGroarty"
puts "\tTyler Rollins"
puts "\tRichard Curteis"
puts "\tAnna Yanova"
puts "\tAndrew Cumine"
puts "\n"
	